site_name: Wealth-OS
site_url: https://alphatecau.github.io/Wealth-OS/
repo_url: https://github.com/alphatecau/Wealth-OS
theme:
  name: material
  palette:
    - scheme: slate
      primary: amber
      accent: deep orange
nav:
  - Home: index.md
  - 01-Strategy:
      - Overview: 01-Strategy/README.md
  - 02-Finance:
      - Accounts: 02-Finance/accounts.md
  - 03-Offers:
      - Core Offer: 03-Offers/core-offer.md
  - 04-GTM:
      - Positioning: 04-GTM/positioning.md
  - 05-Content:
      - Overview: 05-Content/README.md
  - 06-Systems:
      - Overview: 06-Systems/README.md
  - 07-Metrics:
      - Overview: 07-Metrics/README.md
  - Newsletter: newsletter/index.md
  - Premium: premium/index.md
  - 01-Strategy:
      - 01-Strategy/vision.md
      - 01-Strategy/moat.md
      - 01-Strategy/compass.md
  - 01-Strategy:
      - 01-Strategy/vision.md
      - 01-Strategy/moat.md
      - 01-Strategy/compass.md
extra_javascript:
  - assets/js/analytics.js
