name: CI & Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2
      - name: Run Markdown Lint
        run: markdownlint-cli2 "docs/**/*.md"
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install MkDocs + Material
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin
      - name: Build MkDocs
        run: mkdocs build --strict
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install MkDocs + Material
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin
      - name: Deploy MkDocs to GitHub Pages
        run: mkdocs gh-deploy --force
