name: Markdown CI
on:
  push:
    paths: ["**/*.md","**/*.mdx",".markdownlint.jsonc"]
  pull_request:
    paths: ["**/*.md","**/*.mdx",".markdownlint.jsonc"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: |
            **/*.md
            **/*.mdx
